/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import javax.swing.JOptionPane;

public class App {
    private static final String HELLO ="Hello world.";
    public String getGreeting() {
        return HELLO;
    }

    public static void main(String[] args) 
    {
        int x = 1;
        int y = 66;
        JOptionPane.showMessageDialog(null,x+y);
    }
}
