/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import javax.swing.JOptionPane;

public class App {
    private static final String HELLO ="Hello world.";
    public String getGreeting() {
        return HELLO;
    }
    
    public int test1(){
	   
        int t = 1;
    }

    public void test2(){
        System.out.println("Hello");
        System.out.println("Hello");
    }

    public void test3(){
        System.out.println("Hello");
        System.out.println("Hello");
    }


    public static void main(String[] args) 
    {
        int x = 1;
        int y = 66;
        JOptionPane.showMessageDialog(null,x+y);
    }
}
